// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1BsY51uJiHNRh9AJiQ69KsGJgG6fELxg',
    appId: '1:85779195975:web:571d22634a189366116962',
    messagingSenderId: '85779195975',
    projectId: 'kcbaby-7a088',
    authDomain: 'kcbaby-7a088.firebaseapp.com',
    storageBucket: 'kcbaby-7a088.appspot.com',
    measurementId: 'G-00EKGBMPZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD4abcEPSXLYzUGCKOL0UDETrJUxU0wTc',
    appId: '1:85779195975:android:9cf6191bb4595491116962',
    messagingSenderId: '85779195975',
    projectId: 'kcbaby-7a088',
    storageBucket: 'kcbaby-7a088.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGqHjjdHlDSEpQhXUSOtpCSdfxqw-WRJQ',
    appId: '1:85779195975:ios:a520bed299e76ae3116962',
    messagingSenderId: '85779195975',
    projectId: 'kcbaby-7a088',
    storageBucket: 'kcbaby-7a088.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGqHjjdHlDSEpQhXUSOtpCSdfxqw-WRJQ',
    appId: '1:85779195975:ios:e71cd426e5200182116962',
    messagingSenderId: '85779195975',
    projectId: 'kcbaby-7a088',
    storageBucket: 'kcbaby-7a088.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
